package work.assisjrs.springBootCrudBasico;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'assis' at '2/1/17 11:13 PM' with Gradle 2.14.1
 *
 * @author assis, @date 2/1/17 11:13 PM
 */
@SpringBootApplication
public class AppMain {
	public static void main(String... args) {
		SpringApplication.run(AppMain.class, args);
	}
}
